### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by leolorenzoluis** [fable-compiler/fable-getting-started#3] opened 2016-12-02 08:13 UTC
Using the current repository, using `yarn run watch` triggers an infinite recompilation when a file is changed.

I'm using macOS.

```
Change: /dist/umd/Main.js.map at 3:11:24 AM
Bundling...
Bundling...
[BUNDLE ERROR] Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```

**Comment by Pauan** [comment] 2016-12-03 00:03
That's odd. I just upgraded all of the dependencies. Please `git pull` and then try again.

**Comment by leolorenzoluis** [comment] 2016-12-03 07:26
Could you try using macOS and mono?  I have a feeling its related to it

**Comment by Pauan** [comment] 2016-12-03 07:36
@leolorenzoluis I don't own a Mac, I'm on Linux (with Mono). But I asked in Gitter and somebody else said it worked for them. Did you try again with the latest version of this repository?

By the way, the error you showed is almost certainly an error in JavaScript, possibly related to Rollup. I doubt it has anything to do with OSX or Mono, but I could be wrong.

**Comment by leolorenzoluis** [comment] 2016-12-03 07:44
Updating packages, fixes it. Hmm, so was it related to fable power pack?

**Comment by Pauan** [comment] 2016-12-03 09:07
@leolorenzoluis It's possible. Or it could have been related to `fable-compiler`, `fable-core`, or `rollup`, since all of those packages were also updated.

If you want to investigate this further, I would suggest seeing if [this commit](https://github.com/fable-compiler/fable-getting-started/commit/88c9734192ea3d4ee7b209f003f7dc117c348030) causes the problem or not.

**Comment by leolorenzoluis** [comment] 2016-12-03 22:01
I am not sure what happened, but apparently that didnt fix it. I see in my activity monitor that monosgen is consuming >100% CPU. To me it looks like there was an infinite loop on the watch that caused this?

**Comment by alfonsogarciacaro** [comment] 2016-12-04 11:19
The files are being watched by Node with the chokidar package, so I guess it's not Mono's fault. I had a similar problem (not sure if it's exactly the same) when bundling too frequently. At the moment there's no logic to queue the bundles so there may be race conditions (again, not sure if this is the cause of this particular problem). I just put a minimal interval of 3 seconds between changes to prevent compilations too quickly after the other.

**Comment by leolorenzoluis** [comment] 2016-12-04 20:33
Referencing https://github.com/rollup/rollup-watch/issues/28 from @Pauan where he thinks it's the issue.

**Comment by Pauan** [comment] 2016-12-05 16:25
@leolorenzoluis I originally thought it was related to `rollup-watch`, but Fable doesn't use `rollup-watch`, it uses [`chokidar`](https://github.com/paulmillr/chokidar)

There are some issues related to `chokidar` on Mac:

https://github.com/paulmillr/chokidar/issues/550
https://github.com/paulmillr/chokidar/issues/447

I don't think they're related to this, though. I think it's either a bug with Rollup or a bug with Fable.

**Comment by alfonsogarciacaro** [comment] 2016-12-06 11:32
Can you please try with latest compiler version? I'm not sure yet what the problem is, but I made some modifications to make bundling work better in watch mode.

**Comment by rmunn** [comment] 2017-01-12 12:19
Getting this myself, on Linux Mint. Looks like the watcher is triggering off the output files, which triggers another compilation, which means the output file changes again, and we infiloop. I'm invoking the watcher via `yarn`, as follows:

```sh
rmunn@mint:~/code/fsharp/fable-words (master) $ yarn run watch
yarn run v0.18.1
$ fable --target umd --watch
fable-compiler 0.7.7: Start compilation...
Compiled src/fs/Message.js at 7:05:35 PM
Compiled js_includes/Message.js at 7:05:35 PM
Compiled src/fs/Main.js at 7:05:36 PM
Bundling...
Bundled Main.js at 7:05:36 PM
Watching /home/rmunn/code/fsharp/fable-words
Press Enter to terminate process.
change: /home/rmunn/code/fsharp/fable-words/.git/FETCH_HEAD at 7:05:39 PM
Bundling...
Bundled Main.js at 7:05:40 PM
change: /home/rmunn/code/fsharp/fable-words/dist/umd/Main.js at 7:05:40 PM
change: /home/rmunn/code/fsharp/fable-words/dist/umd/Main.js.map at 7:05:40 PM
Bundling...
Bundled Main.js at 7:05:40 PM
Bundling...
Bundled Main.js at 7:05:40 PM
change: /home/rmunn/code/fsharp/fable-words/dist/umd/Main.js at 7:05:40 PM
change: /home/rmunn/code/fsharp/fable-words/dist/umd/Main.js.map at 7:05:40 PM
Bundling...
Bundled Main.js at 7:05:40 PM
Bundling...
Bundled Main.js at 7:05:40 PM
change: /home/rmunn/code/fsharp/fable-words/dist/umd/Main.js at 7:05:40 PM
change: /home/rmunn/code/fsharp/fable-words/dist/umd/Main.js.map at 7:05:40 PM
Bundling...
Bundled Main.js at 7:05:40 PM
```

And so on until the bundler finally gives up with "Maximum call stack size exceeded".

I'm just getting started on this project, so my `fableconfig.json` is still the default one from [the getting-started repo](https://github.com/fable-compiler/fable-getting-started/):

```json
{
  "sourceMaps": true,
  "targets": {
    "umd": {
      "projFile": "./Main.fsproj",
      "rollup": {
        "dest": "./dist/umd/Main.js",
        "format": "umd"
      }
    },
    "test": {
      "projFile": [
        "./Main.fsproj",
        "./test/Test.fsproj"
      ],
      "outDir": "./dist/test",
      "module": "commonjs",
      "coreLib": "fable-core/umd",
      "plugins": ["./node_modules/fable-plugins-nunit/Fable.Plugins.NUnit.dll"],
      "scripts": {
        "postbuild": "mocha --reporter min --colors --sort --recursive ./dist/test/test/fs"
      }
    }
  }
}
```

My `package.json` just has the project name and owner configured:

```json
{
  "name": "fable-words",
  "description": "First attempt at a single-page app with Fable",
  "version": "0.0.1",
  "repository": "bitbucket:rmunn/fable-words",
  "main": "./dist/umd/Main.js",
  "license": "MIT",
  "devDependencies": {
    "fable-compiler": "^0.7.7",
    "fable-core": "^0.7.6",
    "fable-plugins-nunit": "^0.7.1",
    "fable-powerpack": "^0.0.14",
    "mocha": "^3.1.2"
  },
  "scripts": {
    "prepublish": "npm run build",
    "build": "fable --target umd",
    "watch": "fable --target umd --watch",
    "test": "fable --target test"
  }
}
```

I haven't yet made any significant changes to my `Main.fs`, just added a second `console.log` call to check that the compilation watcher is working.

**Comment by rmunn** [comment] 2017-01-12 12:35
Looks like it's precisely what I thought it was: the watcher is watching its own output directory! See the `chokidar` call in [Fable/watch.ts](https://github.com/fable-compiler/Fable/blob/75d8b97b653f5b15d358ace9db41be3088bca3de/src/fable/Fable.Client.Node/ts/watch.ts#L50): it's only ignoring `node_modules`. I edited my local copy of `fable.js` and added the `dist/umd` directory to be ignored, and the infinite watcher loop stopped triggering. (Of course, a real fix would need to extract the correct output directory from `fableconfig.json`, rather than hardcoding a directory to be ignored).

I'll open a bug on Fable to track this, since that's where the fix will be needed.

**Comment by rmunn** [comment] 2017-01-12 12:48
Never mind. I simply hadn't run `yarn upgrade`. A simple upgrade pulled in a later version of `fable-compiler` which actually had the `isFSharpFile` call, and there was no more watcher loop.

So this issue really should be renamed to "Please upgrade the `fable-compiler` version in the getting-started repo". :grin:

**Comment by Pauan** [comment] 2017-01-13 02:18
@rmunn Good catch, I've upgraded the version of `fable-compiler`. I think we can close this now. Feel free to reopen if it's still a problem.

**Closed by Pauan** 2017-01-13 02:18 UTC
